### ISSUE TITLE
Format of date literal in stats_list

### ISSUE THREAD

**Issue by dserban** [sailthru/sailthru-python-client#50]
```
def stats_list(self, list=None, date=None):
```
Which format does `date` have to be in? E.g. `03-04-2015`, `20150403` etc.
The `YYYYMMDD` format appears to yield good results, but I'd like to have a clear cut statement from the devs.

Thanks.

**Comment by Dude-X** [comment]
Our documentation states that dates should be in the YYYY-MM-DD. However YYYYMMDD is also acceptable as you have tested. So long it's a string variable.

**Comment by dserban** [comment]
Thanks for the answer.
Closing as solved.
