### ISSUE TITLE
SailthruClient.multi_send lacks schedule_time parameter

### ISSUE THREAD

**Issue by Gennady-Andreyev** [sailthru/sailthru-python-client#54]
Hi all!

When trying to use `SailthruClient.send` and `SailthruClient.multi_send` interchangeably (depending on how many users I need to email), I've faced an issue related to the fact the two methods have different signatures.

The code looks roughly like this:

```
sc = SailthruClient(SAILTHRU_API_KEY, SAILTHRU_SECRET)
send_method = getattr(sc, 'multi_send' if isinstance(to_email, list) else 'send')
response = send_method(template_name, to_email, email_args, schedule_time=send_on)
```

You can see, that it raises `TypeError: multi_send() got an unexpected keyword argument 'schedule_time'` when `to_email` is a list.

My **expectation** was that `send` would be a proxy of `multi_send`, since the former is logically just a corner case of the latter. However, **actually** both methods turn out to implement [almost identical code](https://github.com/sailthru/sailthru-python-client/blob/master/sailthru/sailthru_client.py#L63) while having different signatures.

Is there a good reason why `send` differs from `multi_send` signature-wise and implementation of the two is not quite _DRYish_? 

I'd be eager to submit a pull request with a fix if you found that reasonable.

Thanks,
Gennady

**Comment by Smohapatra** [comment]
Apologies for the late reply, you are right, multi_send sends an email template to multiple email addresses, so it just acts like a wrapper on top of the send functionality. Please refer to https://getstarted.sailthru.com/developers/api/send/ for more info.

I have now added the support for passing a schedule_time for multi_sends, which will enable sending to all the email address based on that same schedule_time passed. Also its an optional parameter.

**Comment by Gennady-Andreyev** [comment]
Great news, thank you for looking into this!
