### ISSUE TITLE
ssl SailthruClientError with python 2.7

### ISSUE THREAD

**Issue by notifytovishal** [sailthru/sailthru-python-client#60]
Hi All,
   After a bunch of successfull calls, the client calls fails with the following error. Digging this, I found that this might be an issue with the use of request module in sailthru_http_request method in sailthru_http.py. 

`File "../lib/python2.7/site-packages/sailthru/sailthru_client.py", line 678, in api_post
    return self._api_request(action, data, 'POST')
  File "../lib/python2.7/site-packages/sailthru/sailthru_client.py", line 710, in _api_request
    return self._http_request(self.api_url+'/'+action, self._prepare_json_payload(data), request_type)
  File "../lib/python2.7/site-packages/sailthru/sailthru_client.py", line 714, in _http_request
    return sailthru_http_request(url, data, method, file_data)
  File "../lib/python2.7/site-packages/sailthru/sailthru_http.py", line 47, in sailthru_http_request
    raise SailthruClientError(str(e))
SailthruClientError: EOF occurred in violation of protocol (_ssl.c:581)
 ERROR - EOF occurred in violation of protocol (_ssl.c:581)
`

Could you please look into this. We have tried this with the latest sailthru client version as well. 

Thanks !!

**Comment by notifytovishal** [comment]
Also some discussion here
https://github.com/kennethreitz/requests/issues/3006

**Comment by Smohapatra** [comment]
I haven't been able to replicate the issue on my end, going to close it for now, please reach out if this occurs again.
